services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - VLLM_HOST=${VLLM_HOST:-http://localhost:8081}
      - VLLM_ENDPOINT=${VLLM_ENDPOINT:-/api/v1/generate-response}
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads